#!/bin/bash

# find a default username
uname=$(klist | sed -n 's/^.*principal: \([^@]*\)@.*$/\1/p')

# build the PATH variable from scratch, since our environment seems funky
export PATH='/opt/epics/extensions/bin/linux-x86_64:/home/vagrant/bin':"$(
    sed -n 's/^PATH="\([^"]*\)"$/\1/p' \
    /etc/environment
)" 
echo "Launching MEDM screens for LHO."
echo "Press Control-C to quit."
if [ "${uname}" = "" ]; then
    zenity --info --timeout=3 --text 'No LIGO credentials found! Log in using LIGO AUTH button.'
else
    zenity --info --timeout=5 \
        --text "Starting (will take a few seconds); logged in as ${uname}.
If this hangs for a while, file an issue on GitHub."
fi
medm_lho -u "${uname}"
